### ISSUE TITLE
use with shinyDashboard?

### ISSUE THREAD

**Issue by McCartneyAC** [emitanaka/anicon#1]
Hi!

FontAwesome icons are built into shinydashboard directly as part of menus, etc. for example:

```r
menuItem("Reflect", tabName = "reflect", icon = anicon::faa("leaf", animate="bounce")),
```

however, trying to embed an animated icon into this throws the following error:
```
Error in tagAssert(icon, type = "i") : 
  Expected an object with class 'shiny.tag'.
```

Any thoughts on getting anicons to integrate with the icon system used by shinydashboard?

**Comment by emitanaka** [comment]
That will not work as `shinydashboard` has its own way of inserting icons. If you want to embed it in using anicon package capabilities, you will need to do like below:

`menuItem(anicon::faa("leaf", animate="bounce", rtext="Reflect"), tabName = "reflect")`
