### ISSUE TITLE
Blurring text in xaringan slides

### ISSUE THREAD

**Issue by bblodfon** [emitanaka/anicon#6]
Hi,

I've noticed that when you use even just one animated icon, the whole xaringan slide gets blurry (text, other images, etc.). The most evident example can be seen with the [hovering example](https://anicon.netlify.com/#8). Do you know why this happens and if it's possible to not have this effect?

P.S.: Nice idea/package!

**Comment by emitanaka** [comment]
That's funny, I don't see the blurring effect. What browser would you be using?

**Comment by bblodfon** [comment]
Google Chrome (see [test](https://drive.google.com/open?id=1O5xRZaPadkHOcIgnAQ0lNAMoMwV7weK3)). I tested with Firefox and Safari and it works there though (would be nice to have it in Chrome as well :)

**Comment by mitchelloharawild** [comment]
I can also reproduce this with Firefox but it is less noticeable.

**Comment by emitanaka** [comment]
It seems my eyesight is too poor to detect it or I need a higher resolution computer (prob former).
I can't think of a reason why this might happen 🤔

**Comment by bblodfon** [comment]
Interesting, I don't know the "internals" of your package, but maybe we could consult with Yihui from `xaringan` or the developer of `remark.js`?

**Comment by mitchelloharawild** [comment]
I suspect that the issue is more to do with how browsers handle the `scale` css transformation. Perhaps its worth trying if this can be reproduced in other output formats.

**Comment by bblodfon** [comment]
@emitanaka I used your package again today with Chrome and the blurring effect isn't there anymore. 
So Chrome-specific problem, now resolved :tada:
